# Generated by Django 3.0 on 2022-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='guesses',
            field=models.IntegerField(),
        ),
    ]
