# Generated by Django 3.0 on 2022-05-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220523_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='average_guesses',
        ),
    ]
